FROM debian:stable-20250721-slim

# install build tools
RUN apt-get update && apt-get install -y \
  clang cmake

COPY . /app

WORKDIR /app/build

ARG BUILD_TYPE=Release

RUN cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. && cmake --build .

ENTRYPOINT [ "./cpuRayTracer" ]