FROM debian:stable-20250721-slim

# install build tools
RUN apt-get update && apt-get install -y \
  clang cmake

COPY . /app

WORKDIR /app/build

RUN cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .

ENTRYPOINT [ "./cpuRayTracer" ]